remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Brayan Ruiz Diaz
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://avatars.githubusercontent.com/u/128198276?s=400&u=534a42b5cdcbf1346b1cd7be6034dcf97d1cf550&v=4

